// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-7pWtMTg6QU0LlOfQTCy5Q_0-c2wcNc',
    appId: '1:208212694946:web:46224cbb765fdffac104fb',
    messagingSenderId: '208212694946',
    projectId: 'peacely-living',
    authDomain: 'peacely-living.firebaseapp.com',
    storageBucket: 'peacely-living.firebasestorage.app',
    measurementId: 'G-DWJP21727N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl74fwB58Uo9GN3B8N1mlxV2X2juoqYLM',
    appId: '1:208212694946:android:29a3273e6d376633c104fb',
    messagingSenderId: '208212694946',
    projectId: 'peacely-living',
    storageBucket: 'peacely-living.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmV7_kAcRW5HTkrILbqEII0lQnztPyRQE',
    appId: '1:208212694946:ios:7201f2300e4110e3c104fb',
    messagingSenderId: '208212694946',
    projectId: 'peacely-living',
    storageBucket: 'peacely-living.firebasestorage.app',
    iosBundleId: 'com.example.peacely',
  );
}
